[package]
name = "urllogpass"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6.0"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.128"
colored = "1.9.4"
url = "1.7.2"
num_cpus = "1.13.1"
chrono = "0.4.38"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
debug  = false